name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  linteur:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          tools: composer
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test

      - run: npm install

  tests:
  runs-on: ubuntu-latest
  needs: linteur
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: pdo, pdo_mysql
        coverage: none

    - name: Install PHP dependencies
      run: composer install --no-progress --prefer-dist

    - name: Set up environment
      run: cp .env.example .env

    - name: Generate app key
      run: php artisan key:generate

    # - name: Create mysql database
    #   run: |
    #     touch database/database.mysql
    #     php artisan migrate --force

    - name: Run tests
      run: php artisan test
